services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: cyberuser
      POSTGRES_PASSWORD: cyberpass
      POSTGRES_DB: cyberdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=cyberuser
      - DB_PASSWORD=cyberpass
      - DB_NAME=cyberdb
      - DB_PORT=5432
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  sandbox-phishing:
    build: ./sandbox/phishing
    ports:
      - "9081:80"
    networks:
      - app-network
    restart: unless-stopped

  sandbox-email:
    build: ./sandbox/email-client
    ports:
      - "9082:80"
    networks:
      - app-network
    restart: unless-stopped

  sandbox-wifi:
    build: ./sandbox/wifi-hotspot
    ports:
      - "9083:80"
    networks:
      - app-network
    restart: unless-stopped

  sandbox-social:
    build: ./sandbox/social-network
    ports:
      - "9084:80"
    networks:
      - app-network
    restart: unless-stopped

  sandbox-atm:
    build: ./sandbox/atm-simulator
    ports:
      - "9085:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
