spring.application.name=backendJava

spring.datasource.url=jdbc:postgresql://localhost:5434/db
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET_KEY}

# minutes
jwt.access-token-ttl=5

# days
jwt.refresh-token-ttl=30