spring.application.name=backendJava

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_java}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:defaultSecretKeyForDevelopment123456789}

# minutes
jwt.access-token-ttl=5

# days
jwt.refresh-token-ttl=30
